version: "3"
name: "sose05"
services:
  couchdb:
    image: couchdb:3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=gordladmin
      - COUCHDB_PASSWORD=gordlpassword
    volumes:
      - couchdata:/opt/couchdb/data
    
volumes:
  couchdata: